name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDNhZWI4YWYtY2Y0MC00ZTI1LTlmMmEtN2NlNzdmYTU5M2UyIiwidGVuYW50X2lkIjoiMWY1N2MyM2E5MTkzNjRhMTg4MmZjMDFhYzYxZjYwODc0MDIxNTA1NzI2OWVkMjk1MDYyODY0YzljNGE5M2FlNyIsImludGVybmFsX3NlY3JldCI6ImNmODM2MmQyLTIzOTktNGY5Zi04NzEyLTc4YzRmYmRjMzgzMCJ9.tkIq2C8-YFM5Z6QhREpnvK53ySooOUCsQ7AsKj41-h8"
JWT_SECRET="df4dsds0f3234DF"